BEGIN;
DELETE FROM cpl_indikator;
DELETE FROM cpl;
DELETE FROM sub_cpmk;
DELETE FROM cpmk;
DELETE FROM dosen_courses;
DELETE FROM dosen_rps_access;
DELETE FROM dosen_rps_accesses;
DELETE FROM generated_rps;
DELETE FROM template_versions;
DELETE FROM templates;
DELETE FROM courses;
DELETE FROM dosens;
DELETE FROM prodis;
DELETE FROM programs;
DELETE FROM users WHERE role != 'admin';
COMMIT;
SELECT 'Database cleaned successfully!' as status;
SELECT COUNT(*) as total_users FROM users;
SELECT username, email, role FROM users;
